services:
  - type: web
    name: tufan-backend
    runtime: python
    repo: https://github.com/DuruKaygusuz/TUFAN-Web-Page
    branch: Duru-frontend
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false